services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agence_voyage_app
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://zeynab:nouveaumotdepasse@postgres:5432/agence_voyage?schema=public
      JWT_SECRET: voyage221-secret-key
      JWT_EXPIRES_IN: 24h
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: agence_voyage_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: agence_voyage
      POSTGRES_USER: zeynab
      POSTGRES_PASSWORD: nouveaumotdepasse
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zeynab -d agence_voyage"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pg_data:
