- name: Deploy Docker Compose App
  hosts: ec2
  become: true

  vars:
    project_path: /home/ubuntu/VOYAGE-221

  tasks:
    - name: Pull latest code
      git:
        repo: 'https://github.com/nabzey/VOYAGE-221.git'
        dest: "{{ project_path }}"
        version: main

    - name: Pull Docker images
      command: docker compose pull
      args:
        chdir: "{{ project_path }}"

    - name: Start containers
      command: docker compose up -d
      args:
        chdir: "{{ project_path }}"

    - name: Clean unused images
      command: docker image prune -f
